### ISSUE TITLE
OSX: Mouse input

### ISSUE THREAD

**Issue by bmcorser** [shockham/caper#1]
It compiles and runs!

But at the slightest finger of mouse input ...
![caper-mouse-60fps](https://cloud.githubusercontent.com/assets/1449387/13901689/b1d66cbc-ee23-11e5-91a9-aa2ce65c0d86.gif)

**Comment by shockham** [comment]
If you look [here](https://github.com/shockham/caper/blob/master/examples/perlin.rs#L20) in the perlin example the `mouse_speed` variable sets the mouse sensitivity. Does that help?

**Comment by bmcorser** [comment]
Hmmm, that helps show what's happening.

``` diff
diff --git a/examples/perlin.rs b/examples/perlin.rs
index c77767e..ef3d263 100644
--- a/examples/perlin.rs
+++ b/examples/perlin.rs
@@ -17,7 +17,7 @@ fn main() {
     let map_size = 50f32;
     let fixed_val = -(map_size/2f32);
     let move_speed = 0.05f32;
-    let mouse_speed = 3f32;
+    let mouse_speed = 0.05f32;

     let mut pseu_cam_pos = (0f32, 0f32);
     let sphere_pos = (8f32, 10f32);
diff --git a/src/input.rs b/src/input.rs
index 11cb87d..c8e3eb3 100644
--- a/src/input.rs
+++ b/src/input.rs
@@ -42,6 +42,7 @@ impl Input {
                 },
                 MouseMoved(a) => {
                     let mouse_diff = ((width / 2) as i32 - a.0, (height / 2) as i32 - a.1);
+                    println!("{:?} {:?}", mouse_diff.0, mouse_diff.1);
                     self.mouse_delta.0 = (mouse_diff.0 as f32)/(width as f32);
                     self.mouse_delta.1 = (mouse_diff.1 as f32)/(height as f32);
                     self.mouse_pos = a;
```

Slowing the mouse down, I can see that moving the mouse in any direction results in the camera rotating down and to the right ... this is what I see in the logging output:

```
-655 -411
-652 -408
-646 -406
-646 -406
-644 -406
...
```

I should also probably mention that I'm using the touchpad on my Macbook. I did have a glance through the issue trackers for Gluim and Glutin for upstream bugs but could find none.

Feel free to leave this issue open if you want. I'll definitely be keeping an eye on this repo!

:sparkles:

**Comment by shockham** [comment]
Cool, cheers for digging into it.

Wasn't getting it on my macbook, so figured it was probably related to hidpi displays.
So on the line

``` rust
let (width, height) = self.display.get_framebuffer_dimensions(); 
```

where the [framebuffer dimensions are returned](https://github.com/shockham/caper/blob/master/src/renderer.rs#L138) they are half what they should be (1280x800 on a 2560x1600 display) which throws off the mouse_diff calculation. Just going to test using `window.hidpi_factor()` to take into account for this.

Maybe https://github.com/tomaka/glutin/issues/503 might be related too.

**Comment by shockham** [comment]
Ok, https://github.com/shockham/caper/commit/b4265ba93e20c3b50b870ff103eb779dc2cd62b4 should sort this.

**Comment by bmcorser** [comment]
Ah cracking. :+1:  Closing this.

Digging the shader updates too.
