### ISSUE TITLE
Cocoa compile error Mac

### ISSUE THREAD

**Issue by Roba1993** [shockham/caper#11]
Hey,

first of all, I really like what you are building up here, all alone. You have my full respect and I hope, you can stay as motivated as you are right now for this project.

Unfortunately I can't use your crate because Cocoa is not compiling. Do you know an answer?

Compiling cocoa v0.3.3
error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:251:45
    |
251 |     unsafe fn sharedApplication(_: Self) -> id {
    |                                             ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:326:46
    |
326 |     unsafe fn currentApplication(_: Self) -> id {
    |                                              ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:339:31
    |
339 |     unsafe fn new(_: Self) -> id {
    |                               ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:364:33
    |
364 |     unsafe fn alloc(_: Self) -> id {
    |                                 ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:368:31
    |
368 |     unsafe fn new(_: Self) -> id {
    |                               ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:372:41
    |
372 |     unsafe fn separatorItem(_: Self) -> id {
    |                                         ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:422:33
    |
422 |     unsafe fn alloc(_: Self) -> id {
    |                                 ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
    --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:1269:33
     |
1269 |     unsafe fn alloc(_: Self) -> id {
     |                                 ^^ `Self` does not have a constant size known at compile-time
     |
     = help: the trait `std::marker::Sized` is not implemented for `Self`
     = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
    --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:1364:33
     |
1364 |     unsafe fn alloc(_: Self) -> id {
     |                                 ^^ `Self` does not have a constant size known at compile-time
     |
     = help: the trait `std::marker::Sized` is not implemented for `Self`
     = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
    --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:1393:33
     |
1393 |     unsafe fn alloc(_: Self) -> id {
     |                                 ^^ `Self` does not have a constant size known at compile-time
     |
     = help: the trait `std::marker::Sized` is not implemented for `Self`
     = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
    --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:1427:33
     |
1427 |     unsafe fn alloc(_: Self) -> id {
     |                                 ^^ `Self` does not have a constant size known at compile-time
     |
     = help: the trait `std::marker::Sized` is not implemented for `Self`
     = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
    --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:2410:33
     |
2410 |     unsafe fn alloc(_: Self) -> id {
     |                                 ^^ `Self` does not have a constant size known at compile-time
     |
     = help: the trait `std::marker::Sized` is not implemented for `Self`
     = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
    --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/appkit.rs:2482:43
     |
2482 |     unsafe fn systemStatusBar(_: Self) -> id {
     |                                           ^^ `Self` does not have a constant size known at compile-time
     |
     = help: the trait `std::marker::Sized` is not implemented for `Self`
     = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:133:31
    |
133 |     unsafe fn new(_: Self) -> id {
    |                               ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:152:39
    |
152 |     unsafe fn processInfo(_: Self) -> id {
    |                                       ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:168:58
    |
168 |     unsafe fn valueWithPoint(_: Self, point: NSPoint) -> id {
    |                                                          ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:172:55
    |
172 |     unsafe fn valueWithSize(_: Self, size: NSSize) -> id {
    |                                                       ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:181:33
    |
181 |     unsafe fn array(_: Self) -> id {
    |                                 ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:185:60
    |
185 |     unsafe fn arrayWithObjects(_: Self, objects: &[id]) -> id {
    |                                                            ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:190:55
    |
190 |     unsafe fn arrayWithObject(_: Self, object: id) -> id {
    |                                                       ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:209:33
    |
209 |     unsafe fn alloc(_: Self) -> id {
    |                                 ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:248:39
    |
248 |     unsafe fn distantPast(_: Self) -> id {
    |                                       ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
   --> /Users/roba/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.3.3/src/foundation.rs:252:41
    |
252 |     unsafe fn distantFuture(_: Self) -> id {
    |                                         ^^ `Self` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `Self`
    = help: consider adding a `where Self: std::marker::Sized` bound

error: aborting due to 23 previous errors

**Comment by shockham** [comment]
Hello, Thanks!

Yeah, I am getting this error too when I build using nightly.
Will try and dig into it a little more over the next couple days.

For the time being should build fine on stable.

Thanks for reporting.

**Comment by Roba1993** [comment]
With stable it works. 
Strange error...

**Comment by shockham** [comment]
Sorry haven't updated on this in a while.

Basically, this is coming up a couple of dependencies downstream caper -> glium -> glutin -> cocoa. Though the issue appears to fixed in the newer versions of the cocoa crate, which means the issue might be sorted in the new version of glium, 0.17.

Have created a branch to switch to this as it has breaking changes, some other deps need to be updated for it too though.

**Comment by shockham** [comment]
Have merged this branch now with #12, so master should be all good with nightly on macOS.

Going to go ahead and close this, but feel free to re-open if you are still getting the issue.
