### ISSUE TITLE
Screen flashing/objects move very fast.

### ISSUE THREAD

**Issue by tinywombat765** [shockham/caper#16]
In the examples that use the handle_fp_inputs function the objects on the screen appear the flash or are moving very fast around me.  FYI this only happens on one of my computers.  It is running Manjaro Linux

**Comment by tinywombat765** [comment]
![animation_small](https://user-images.githubusercontent.com/6034238/32448987-682bab90-c2de-11e7-9062-9bcfac459a7a.gif)

**Comment by tinywombat765** [comment]
I think what's happening is the camera is spinner around very fast.

**Comment by shockham** [comment]
Thanks for reporting.

I think this may have something to do with dpi, using xrandr (something like `xrandr --dpi 72` depending on your monitor) to explicitly set it.

When I get some time will look into sorting this internally.

**Comment by shockham** [comment]
Ok, had a deeper look into this and as the input lib [volition](https://github.com/shockham/volition) uses the hidpi_factor fn from [winit](https://github.com/tomaka/winit) then if you are also using x11 then tomaka/winit#169 becomes a problem (so setting dpi to 96, input seems to work fine).

Think I can remove reliance on hidpi_factor for input without any problems, so will look at doing that.

**Comment by bddap** [comment]
Ran into this on macOS too.

**Comment by shockham** [comment]
@bddap ok thanks, will have a look into it, think it might be related to the above fix for linux.
