### ISSUE TITLE
impl Default for types rather than using builder's field-level defaults

### ISSUE THREAD

**Issue by TedDriggs** [shockham/caper#23]
With `derive_builder` supporting serde-style usage of struct level defaults, `Transform` et al. could be more idiomatically written as:

```rust
/// struct for handling transform data
#[derive(Builder, Copy, Clone, Serialize, Deserialize, PartialEq)]
#[builder(default)]
pub struct Transform {
    /// The position of the transform
    pub pos: Vector3,
    /// The rotation of the transform
    pub rot: Quaternion,
    /// The scale of the transform
    pub scale: Vector3,
    /// Whether the transform is currently active/should be rendered
    pub active: bool,
    /// Whether the transform is frustum culled
    pub cull: bool,
}

impl Default for Transform {
    fn default() -> Self {
        Transform {
            pos: (0f32, 0f32, 0f32),
            rot: (0f32, 0f32, 0f32, 0f32),
            scale: (1f32, 1f32, 1f32),
            active: true,
            cull: true,
         }
    }
}
```

This change would also enable using these types in more contexts.

**Comment by TedDriggs** [comment]
This will depend on colin-kiegel/rust-derive-builder#127 being fixed, or else `RenderItem<T>` won't compile.

**Comment by shockham** [comment]
Thanks, hadn't seen this, is a lot cleaner.

If you have already made the changes to the types you are welcome to put in a PR, though I guess once that issue is fixed. 

No worries if not, I will then go ahead and make the changes.

**Comment by TedDriggs** [comment]
I’ve got the PR ready, just waiting on publishing 0.5.2 with the mentioned fix.

**Comment by TedDriggs** [comment]
@shockham quick update on this: I'm blocked on getting publishing credentials to update `derive_builder`. I can push my changes if you want and you can try them against master, but I don't know when I'll be able to publish the 0.5.2/0.6.0 update.

**Comment by shockham** [comment]
Yeah sure, that would be great thanks!

I have a couple of other unpublished dependencies pulling from git right now so wouldn't mind doing the same with `derive_builder` temporarily too.

**Comment by TedDriggs** [comment]
The 0.6.0 update is finally published, so you should be able to use it now.
