### ISSUE TITLE
Don't require owned string in get_render_item_by_name

### ISSUE THREAD

**Issue by TedDriggs** [shockham/caper#24]
[`get_render_item_by_name`](https://github.com/shockham/caper/blob/8d3ff71ca6f2cc1dafdc9f20df15b8994f2e9847/src/game.rs#L112) doesn't seem to need ownership of the passed-in string, so having it accept `&str` would avoid unnecessary allocations and improve the ergonomics of using it with static strings.

In the same fix, it'd probably make sense to change the [impl of that method](https://github.com/shockham/caper/blob/master/src/game.rs#L137) to be more idiomatic:

```rust
self.render_items.iter_mut().find(|item| item.name == name)
```

**Comment by shockham** [comment]
Nice suggestion, thanks! Just went ahead and commited this as wanted to test with some projects I am using it for.
