### ISSUE TITLE
OsError("GL context creation failed")

### ISSUE THREAD

**Issue by TheRadioGuy** [shockham/caper#28]
https://github.com/shockham/caper/blob/a5eaec62def1738259b6ae064706d3fc201610ba/src/renderer/mod.rs#L100

Does caper supports open gl 2.1?

**Comment by shockham** [comment]
No sorry, it doesn't as it makes use of instancing, as well as tessellation shaders.

Is there a specific reason why you wanted to use 2.1?

**Comment by TheRadioGuy** [comment]
My laptop with Intel gma 4500 supports only OpenGl and only 2.1 version :(

So I can't find any rust game engines with OpenGl 2.1
