### ISSUE TITLE
Compile Problems

### ISSUE THREAD

**Issue by MrMonotone** [shockham/caper#3]
Hello I am trying to compile the transforms example with the latest code. When I run the example, it exits with this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` v
alue: NoVersion', src/libcore/result.rs:837
```

I am a feeling it has something to do with shaders and opengl. I have successfully run the samples for imgui and glium though so, I am at a loss.
I am new to rust so if you could point me in the right direction to solve my problem I would be really appreciative.
MM
Here is the backtrace:

```
1.14.0/src/libcore/result.rs:737
  11:     0x56267194d830 - caper::shader::Shaders::new::h3e9b58a1d
66d849a
                        at /home/nicholas/Documents/Code/rust_proj
ects/caper/src/shader/mod.rs:22
  12:     0x56267194a629 - caper::renderer::Renderer::new::h716119
fc4271156e
                        at /home/nicholas/Documents/Code/rust_proj
ects/caper/src/renderer.rs:73
  13:     0x5626718c8310 - transforms::main::h3fda41e71022afff
                        at /home/nicholas/Documents/Code/rust_proj
ects/caper/examples/transforms.rs:117
  14:     0x562671c2ea3a - __rust_maybe_catch_panic
                        at /home/build/YPKG/root/rust/build/rustc-
1.14.0/src/libpanic_unwind/lib.rs:97
  15:     0x562671c264b5 - std::rt::lang_start::hd661476ce2fc2931
                        at /home/build/YPKG/root/rust/build/rustc-
1.14.0/src/libstd/panicking.rs:332
                        at /home/build/YPKG/root/rust/build/rustc-
1.14.0/src/libstd/panic.rs:351
                        at /home/build/YPKG/root/rust/build/rustc-
1.14.0/src/libstd/rt.rs:57
  16:     0x5626718d65e2 - main
  17:     0x7f815742a480 - __libc_start_main
  18:     0x56267177e3d9 - _start
                        at ../sysdeps/x86_64/start.S:120
  19:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/examples/tr
ansforms` (exit code: 101)
```

**Comment by shockham** [comment]
Hi! Thanks for reporting. Yeah this does sound like this is related to the OpenGL version. At the moment out of the box caper is geared towards at least OpenGL 4.0 due to the use of tessellation shaders.
Glium and imgui target a much wider range of versions.

What platform & gpu are you running this on? (there is a glium example called [info](https://github.com/tomaka/glium/blob/master/examples/info.rs) that prints out all the OpenGL version/gpu info :) )

**Comment by MrMonotone** [comment]
Linux Gtx 970 with 370 something driver not the latest though my distro (Solus) hasn't updated it.

**Comment by MrMonotone** [comment]
I will update later exact info

**Comment by MrMonotone** [comment]
glium info
OpenGL context verson: 3.2.0 NVIDIA 375.39
OpenGL context flags: debug
OpenGL profile mask: core
OpenGL robustness strategy: none
OpenGL context renderer: GeForce GTX 970/PCIe/SSE2
OpenGL context vendor: NVIDIA Corporation

My driver says: OpenGL version string: 4.5.0 NVIDIA 375.39

I guess it is because I am using 3.0 on glium.is it a setting I need to force?

**Comment by MrMonotone** [comment]
I fixed it by adding this to renderer.rs . I do not know what the "right" fix is or else I would submit a pull request... This is what I added:
```
// Render.rs: 5
use glium::glutin::{ WindowBuilder, get_primary_monitor, GlRequest, Api }; //Change here
// Render.rs: 63
            .with_gl(GlRequest::Specific(Api::OpenGl, (4, 5))) // Change here
```
GlRequest::Latest did not work for me on my linux machine.

**Comment by shockham** [comment]
Yeah that seems like a tidy fix to me, is the kind of thing I had in mind. Thanks!

Though only difference I might go with is having `GlRequest::Specific(Api::OpenGl, (4, 0))` does that still work for you? (macOS only supports [up to OpenGL 4.1](https://developer.apple.com/opengl/capabilities/))

Happy for you to put in a pull request for that change.

**Comment by MrMonotone** [comment]
#4 closes this issue.
