### ISSUE TITLE
Add 3D audio capabilities

### ISSUE THREAD

**Issue by ThePerkinrex** [shockham/caper#33]
The Audi system is really minimalist and simple to understand, but 3D audio could be pretty useful. I have used a library called ambisonic, based on rodio which implements 3D audio really well, but I don't think fits the minimalist approach. Maybe the audio system could be extended to incorporate it, or just base a 3D audio system on it

**Comment by shockham** [comment]
3D audio would be super interesting, have thought about it before as it would be fun to play with.

Considering the audio system is completely separate and just a re-export, will check out that lib and see if/how it might make sense to incorporate. Whether it be a feature to select the audio lib, or even just one to remove the current one as suggested in #34 so you can BYO.
