### ISSUE TITLE
Add Physics and sound as features

### ISSUE THREAD

**Issue by ThePerkinrex** [shockham/caper#34]
Adding those as features could lead to those being disabled if not needed, so that the library being compiled is so much smaller. The would obviously be on by default, but I think that would add value to the crate.
Maybe those systems are too integrated into the rest of the library that this isn't possible, but it would be nice.

The engine is amazing btw, it has a really understandable structure, it feels a lot more welcoming than other engines.

**Comment by shockham** [comment]
Thanks! Glad you dig it.

Will have a look into it, fairly certain it is at least poss. for audio. Physics might require more of a think but I will have a play around with it.
