### ISSUE TITLE
Package derive_builder v0.4.4 does not have these features: private_fields

### ISSUE THREAD

**Issue by eibx** [shockham/caper#9]
Hi,

When I'm building it throw the following error.
`Package 'derive_builder v0.4.4' does not have these features: 'private_fields'`

I can't seem to find the feature branch on https://github.com/colin-kiegel/rust-derive-builder neither.

I can easily remove the feature from the Cargo.toml file so it's not really a problem, but just wanted to let you know.

**Comment by shockham** [comment]
Hi, Have you run `cargo update` to get the latest version of derive_builder?
Sorry, I should have put in a more specific version of it, will change now.

You can see the feature in the derive_builder [Cargo.toml](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/Cargo.toml)

(You can read about it in their [changelog](https://github.com/colin-kiegel/rust-derive-builder/blob/f803b11e0c437169eb96cc6734eb4e634c2da175/derive_builder/CHANGELOG.md#deprecated), basically I was getting loads of warnings so decided to switch to private builder defaults early in preparation for the change)

**Comment by eibx** [comment]
Hi, `cargo update` worked. Thanks!

I really thought I tried that, apparently not. Sorry for the inconvenience.

**Comment by shockham** [comment]
No worries, glad it is sorted.
